version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:{{cookiecutter.postgresql_version}}
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB={{cookiecutter.app_name}}db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"

    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"

    networks:
      - postgres-network
  
  {% if cookiecutter.celery_worker != "Do not use Celery" %}
  {% if cookiecutter.celery_worker == "Redis" %}
  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  {% else %}
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.13-management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
  {% endif %}
  {% endif %}

networks:
  postgres-network:
    driver: bridge
